use_default_settings: true

server:
  secret_key: "void-browser-secret-key-2026"
  bind_address: "0.0.0.0:8080"
  base_url: "https://web-production-e2aca.up.railway.app"

search:
  formats:
    - html
    - json
    - rss

engines:
  - name: google
    engine: google
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
